name: Update Server Status

on:
  workflow_dispatch:
    inputs:
      status:
        description: 'Pilih status server (true / false)'
        required: true
        default: 'true'
        type: choice
        options:
          - true
          - false

jobs:
  update_status:
    name: Update Server Status File
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Buat file status.json dengan nilai terbaru
        run: |
          echo "{ \"server_status\": ${STATUS} }" > status.json
        env:
          STATUS: ${{ github.event.inputs.status }}

      - name: Konfigurasi Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit dan Push Perubahan
        run: |
          git add status.json
          git commit -m "Update server_status ke ${STATUS}"
          git push
        env:
          STATUS: ${{ github.event.inputs.status }}