name: Toggle Server Status

on:
  workflow_dispatch:

jobs:
  toggle_status:
    name: Toggle Server Status
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Toggle Status
        id: toggle
        run: |
          if [ -f "status.json" ]; then
            current_status=$(jq -r '.server_status' status.json)
            [[ "$current_status" == "true" ]] && new_status=false || new_status=true
          else
            new_status=false
          fi
          jq -n --argjson status $new_status '{server_status: $status}' > status.json
          echo "status_value=$new_status" >> $GITHUB_OUTPUT

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Commit and Push Changes
        run: |
          git add status.json
          git commit -m "Toggle server status to ${{ steps.toggle.outputs.status_value }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
